### ISSUE TITLE
`classes` attribute broken in report

### ISSUE THREAD

**Issue by omerferhatt** [Renumics/sliceguard#64]
https://github.com/Renumics/sliceguard/blob/3d6fb29c185ce07d6700c3ab04c07792970825ac/sliceguard/sliceguard.py#L431

`self._classes` should be `self.classes`

**Comment by dani2112** [comment]
Thanks @omerferhatt. Fixed in v0.0.35: https://github.com/Renumics/sliceguard/releases/tag/v0.0.35
